### ISSUE TITLE
Merging entry fields

### ISSUE THREAD

**Issue by ghost** [imjakechapman/CraftySocialShare#2]
I have been unable to merge entry fields. I have tried, for example with twitter button

"text": "entry.title"
"text": "{{entry.title}}"

No joy. What am I missing?

**Comment by imjakechapman** [comment]
@cranberry 

you can actually just leave off the quotations like so..

```
{{ SocialBtn('twitter', { "text": entry.title }) }}
```

**Comment by ghost** [comment]
Awesome. Thanks

---

David McInnis
360.483.8441
http://peoplepond.com/davidmcinnis

On Jun 26, 2014, at 9:21 PM, Jake Chapman notifications@github.com wrote:

@cranberry https://github.com/cranberry

you can actually just leave off the quotations like so..

{{ SocialBtn('twitter', { "text": entry.title }) }}
